### ISSUE TITLE
Memory consumption?

### ISSUE THREAD

**Issue by noblige** [valhalla/tyr#121]
I'm using `tyr_simple_service` with California extract (17,473,464 nodes and 3,378,640 ways). I'm observing that memory usage grows with every `route` request I make - and these are not long routes (around 10 miles).
With 500MB RAM machine it uses up all the memory and crashes after about 5 requests.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

ii  libboost1.54-all-dev                1.54.0-4ubuntu3.1      amd64                  Boost C++ Libraries development files (ALL)

Linux maps 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kevinkreiser** [comment]
hey @noblige the default configuration assumes you have 1GB of ram. that is to say that `valhalla.json` has an optional key https://github.com/valhalla/conf/blob/master/valhalla.json#L3 which if not present in the config file will be defaulted to 1mb. this allows the cached tile data to grow until that limit is reached and then purges tiles after it is hit. this hasn't been documented so many apologies for that!

With 500MB of you'd probably want a value somewhere in the 400MB range, so `400000000`.

**Comment by noblige** [comment]
@kevinkreiser I was hoping it was configurable, but could not find the setting. Thanks - I will try that right away!
