### ISSUE TITLE
bug report: location endpoint doesn't respond to 1 location; responds partially to 2 locations

### ISSUE THREAD

**Issue by drewda** [valhalla/tyr#48]
Hi @kevinkreiser,

This request--containing one lat/lon pair--returns a blank body:

`GET http://valhalla.api.dev.mapzen.com/locate?json={%22locations%22:[{%22lat%22:40.335725,%22lon%22:-76.407814}],%22costing%22:%22pedestrian%22}`

----

This request--containing two lat/lon pairs--returns the following response (which only reflects the first, but not the second, lat/lon pair):

`GET http://valhalla.api.dev.mapzen.com/locate?json={%22locations%22:[{%22lat%22:37.775692,%22lon%22:-122.413601},{%22lat%22:40.74455,%22lon%22:-73.990472}],%22costing%22:%22pedestrian%22}`

````json
[
  {
    "input_lon": -122.413605,
    "ways": [
      {
        "correlated_lon": -122.413605,
        "way_id": 8917801,
        "correlated_lat": 37.775692
      }
    ],
    "input_lat": 37.775692
  },
  {
    "input_lon": -122.413605,
    "ways": [
      {
        "correlated_lon": -122.413605,
        "way_id": 8917801,
        "correlated_lat": 37.775692
      }
    ],
    "input_lat": 37.775692
  }
]
````

---

FYI, here are the request/response pairs that Datastore's test suite is currently expecting: https://github.com/transitland/transitland-datastore/blob/388fdb7840cf08e8d66b9d2fade1c0aec4c15d7b/spec/services/tyr_service_spec.rb If any of that's wrong, just let me know, and I'll edit it on our side: https://github.com/transitland/transitland-datastore/pull/62

//cc @irees @dnesbitt61 @gknisely

**Comment by irees** [comment]
I mentioned it to @kevinkreiser in Flowdock the other day; my quick workaround was to just request the same stop twice.

**Comment by kevinkreiser** [comment]
i had fixed the two things that @irees mentioned however we haven't yet updated the instance with the fixes. i will run @drewda 's issues above and fix whatever bugs they have exposed. appologies for the inconveniences.

**Comment by drewda** [comment]
Thanks, @irees, and no worries, @kevinkreiser!

When you're ready for me to re-run (or re-write) the Datastore tests, just let me know.

**Comment by kevinkreiser** [comment]
@drewda confirmed the second issue was because i was only ever looking for the first location in the list... so that was fixed in another pr that recently got merged.

we've got the first cut of the new more stable/faster/parallel/non-blocking service so i'll need to test if the blank body is still happening. after that i'll get the aws instance updated to use the new stuff and i'll let you know when that is ready.

**Comment by drewda** [comment]
Good to know. Thanks, @kevinkreiser

**Comment by drewda** [comment]
Looks like this is fixed and up on dev servers now.

//cc @kevinkreiser

**Comment by kevinkreiser** [comment]
indeed. apologies for not notifying you all sooner!

**Comment by drewda** [comment]
Great, thanks, @kevinkreiser
