### ISSUE TITLE
public transport

### ISSUE THREAD

**Issue by gebrits** [valhalla/tyr#62]
Is public transport routing something that is considered for tyr? 

This could include: 

* fixed schedules or even realtime feeds as input
* cost-function for having to transit

Thoughts?

**Comment by gknisely** [comment]
Yes, we are planning to add transit.  If you're at State of the Map US in
NYC this weekend, we'll be demoing it live. Stay tuned.

 --Greg.

**Comment by gebrits** [comment]
Nope I wish. Any chance it's taped/blogged about? :)

**Comment by yipcma** [comment]
could we use our own gtfs data with the valhalla api?

**Comment by dnesbitt61** [comment]
Not directly at this time. We are still working on transit - both the import pipeline and the algorithms to generate the transit route.  Are you looking for specific GTFS feeds?

**Comment by yipcma** [comment]
@dnesbitt61 i have a particular routes-set in gtfs. Would like to do routing on them, preferably using a routing API so not to do things from scratch (such as building a time-expanded graph using the gtfs feed i got). Any hope or other solutions/API around for this purpose?

**Comment by dnesbitt61** [comment]
We do not route strictly on GTFS. We have a process that imports "modified" GTFS feeds. There needs to be a preprocessing step that adds connections to OSM streets - we are still refining that process. Our multimodal routing currently requires walking at the origin and destination locations (finds nearest walkable OSM ways) - then based on schedule uses the GTFS transit information in between.  It might be possible for you to import OSM data near where you have GTFS feeds, then import both the OSM and GTFS data to build data for your own instance of Valhalla. We have no method of uploading a GTFS feed to us and making it available in our hosted service.

**Comment by yipcma** [comment]
@dnesbitt61  Thank you very much for the followup. Is there some guidance or references we can read on how we host our own vahalla?

**Comment by dnesbitt61** [comment]
https://github.com/valhalla/chef-valhalla has most of the information and scripts for building a Valhalla service.  There is a short sample for downloading an OSM region and building Valhalla tiles from it as well (see the part under Building and Running where it gets an OSM extract from geofabrik and calls the pbfgraphbuilder program). Hooking in GTFS will require a few additional steps, that we have not yet documented but should be possible.

**Comment by yipcma** [comment]
@dnesbitt61 Thank you so much. We've set up an instance of valhalla and the test case run fine on our server. It'd be great if you could give some brief sketches as to those "addition few steps". Look forward to hearing from you soon :)

**Comment by dnesbitt61** [comment]
We are currently reworking our transit import methods. We are working with our partner at Mapzen - Transitland (https://transit.land/) - who is ingesting GTFS feeds, adding community curated information, and implementing a richer station/platform/egress model and a normalized schedule model. We are in SF talking to them this week and developing a plan to use their APIs to ingest transit data. Do you have a specific GTFS feed in mind? Transitland has a way to add a GTFS feed to their repository - in which case we will be able to ingest it into Valhalla. Sorry we don't have a fully developed transit data ingestion pipeline - we have a small team and a partnership with Transitland allows us to focus on routing while they focus on the mechanisms of ingesting GTFS.

**Comment by yipcma** [comment]
@dnesbitt61 Indeed, we have a community bus route feed that has passed the GTFS validator. How long would it take from submitting to transitland till it working in valhalla's routing api/chef valhalla?

**Comment by dnesbitt61** [comment]
I think it will take a few weeks to rework our data import to use the Transitland API. It is our top priority project now so I expect work to progress quickly.  We will update you in a couple weeks,

**Comment by yipcma** [comment]
@dnesbitt61 Hi, just checking in see how it goes with the Transitland API~

**Comment by dnesbitt61** [comment]
We are getting close to having a working import using the Transitland API. We will document the process once we get it working (hopefully in a week or 2). Have you been in touch with Transitland about importing your feed?

**Comment by yipcma** [comment]
this is very exciting. We are incorporating some new changes to the routes and will soon submit a pull request to transitland. Keep up the good work guys :)

**Comment by andreyz** [comment]
Any updates here?

**Comment by dnesbitt61** [comment]
We still have not documented the import process and have some further tuning to do. We hope to announce beta transit routing in January. The plan is still to get data from Transitland. I think they are still finalizing their feed import process.

**Comment by wafisher** [comment]
Is there any update on this? Would love to know what the transit routing capabilities are at this time.

**Comment by drewda** [comment]
@wafisher yes, transit routing is now available through the hosted Mapzen Turn-by-Turn API. More info at:

https://mapzen.com/blog/transit-routing
https://mapzen.com/blog/even-more-transit-routing/
https://mapzen.com/documentation/turn-by-turn/api-reference/ (see the `multimodal` costing profile)

**Comment by andreyz** [comment]
@drewda thanks for updating and sharing recent blog posts on the matter. I have an additional question — any hint on supporting GTFS-RT or compatible realtime updates?

**Comment by drewda** [comment]
@andreyz real-time transit data is a topic we've discussed with a number of potential collaborators and also experimented with ourselves, but we'll be saving it until Transitland and Valhalla provide a real solid foundation and coverage of static schedule data. Please do continue to follow this topic over at https://github.com/transitland/transitland/issues/77
