### ISSUE TITLE
Different result format

### ISSUE THREAD

**Issue by fuCtor** [valhalla/tyr#63]
When make request recieve two different result format:
- top level element is array 
http://valhalla.mapzen.com/viaroute?costing=pedestrian&api_key=API_KEY&instructions=true&loc=57.16719321796962%2C65.50047755241394&loc=57.16511646873044%2C65.4948341846466
- top level element is object
http://valhalla.mapzen.com/viaroute?costing=pedestrian&api_key=API_KEY&instructions=true&loc=57.168129752990176%2C65.4973554611206&loc=57.162614907211484%2C65.49340724945068

**Comment by kevinkreiser** [comment]
A previous version of the code had the array behavior so one of the machines must be out of sync. Will fix asap

**Comment by kevinkreiser** [comment]
should be fixed now (and earlier today...) sorry for the inconvenience
