### ISSUE TITLE
Encoded polyline shape returned doesn't decode properly

### ISSUE THREAD

**Issue by matbeard** [valhalla/tyr#80]
I'm trying to call Valhalla directly and then display the route on a Leaflet map, using the encoded polyline (I know there is an lrm plugin, but I want direct access to the response from TYR).

There is a Leaflet plugin that decodes the polyline shape, but it is returning strange latlng (eg. latitudes in the 500s rather than 50s). I've tried using Googles own decoder, but it also produces these strange results, so I think the problem is with the encoded polyline.

Any suggestions?

EDIT: Ignore this. I just need to adjust the decoding precision. Sorry.

**Comment by kevinkreiser** [comment]
Yep, we use 6 decimals of precision. Can you point me to the code that is doing the decoding? I can show you how to change it to work with 6 decimal places rather than 5

**Comment by kevinkreiser** [comment]
Oh i see you found that out already! Cool no worries!
