### ISSUE TITLE
Missing roundabout exits

### ISSUE THREAD

**Issue by costales** [valhalla/tyr#81]
Hi!

From the JSON in Valhalla https://mapzen.com/projects/valhalla I'm not getting the roundabout exit number.

This is an example: http://paste.ubuntu.com/12646069/
One entry is:
{
      "begin_shape_index":8594,
      "time":13,
      "type":26,
      "end_shape_index":8602,
      "instruction":"Enter the roundabout and take the 1st exit.",
      "length":0.059,
      "verbal_transition_alert_instruction":"Enter roundabout.",
      "verbal_pre_transition_instruction":"Enter the roundabout and take the 1st exit."
   },

If I need to compose the instruction by my self, I haven't the exit number (1st in this case).
It should be filled into the sign.exit_number_elements property.

Thanks a lot in advance!

**Comment by dgearhart** [comment]
@costales sign.exit_number_elements list is for interchange numbers - typically highway exit numbers. The roundabout exit number is a roundabout exit count that is relative from where you entered the roundabout. We can return a roundabout_exit_count value in the response.

**Comment by costales** [comment]
Wow :) Really fast! Thanks a lot!
One question please, when will be this improvement into the API response?

**Comment by dgearhart** [comment]
Your are welcome - thanks for using Valhalla and for the feedback
I will discuss with the team - possibly by the end of the week

**Comment by dgearhart** [comment]
@costales our production servers have been updated to include roundabout_exit_count in the API response

**Comment by costales** [comment]
It works perfect!
Thanks a lot! You are awesome and fast!
