### ISSUE TITLE
Wrong routes with near roundabouts

### ISSUE THREAD

**Issue by costales** [valhalla/tyr#83]
Hi!

I saw a few times, in a road, the route is getting roundabouts, and it shouldn't.

![roundabout](https://cloud.githubusercontent.com/assets/5886786/10462998/2a45d69c-71e2-11e5-967e-0ed6a1a08211.jpg)

Examples:
https://valhalla.mapzen.com/route?json={"locations":[{"lat":43.518974,"lon":-5.685717},{"lat":43.520238,"lon":-5.684821}],"costing":"auto"}&api_key=valhalla-xxxxxx

https://www.openstreetmap.org/edit?editor=potlatch2#map=19/43.51970/-5.68520

or this:
https://valhalla.mapzen.com/route?json={"locations":[{"lat":43.513998,"lon":-5.686398},{"lat":43.512944,"lon":-5.686173}],"costing":"auto"}&api_key=valhalla-xxxxx

https://www.openstreetmap.org/edit?editor=potlatch2#map=19/43.51364/-5.68631

Thanks in advance!!

**Comment by dnesbitt61** [comment]
While looking at this I think we have a good fix for the first case (which is a roundabout) and will push data updates for that sometime next week. The second case is not marked as a roundabout in the OSM data. Do you know if this is really a roundabout and perhaps should be tagged as such? The ways are highway=trunk_link but not roundabouts.

**Comment by costales** [comment]
Thanks David!

FYI too, I'm impressed with the Mapzen quality! For me, the best!

About the second, it's a not normal roundabout, it's more like a desviation
for change the road and go to the left or right :)

A big hug and thanks!

**Comment by dnesbitt61** [comment]
closing this issue - added a new issue mjolnir/#411 to tackle the 2nd case. It is likely due to computation of stop_impact used in transition costing.
