### ISSUE TITLE
Return Error Codes in addition to error string

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/tyr#96]
ReMix requested a return of error codes in addition to error strings. Kevin's comment: 

Right now return non json error. but instead we can return json error and make one part of it the code. Best thing to do would be to subclass std exception, add a code to it and return the json. they can then parse that on their end as if it were normal json.

**Comment by kdiluca** [comment]
This has been fixed!
https://github.com/valhalla/tyr/commit/c5e688bb68afbb961508946beb69f936ef4db9e1

**Comment by dnesbitt61** [comment]
We wanted internal error codes in addition to formatting the response in JSON.
